<a href="https://colab.research.google.com/github/sumitchhipa/python-learning/blob/main/CNN_overview_7nov.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# introduction to cnn
# cnn-> it is working for image related data

In [2]:
# images--> pixels(0-255)--> 0px(black) and 255px(white)
# normalize(0-1)---> 0px(black), 1px (white)
# images


In [4]:
import numpy as np


In [5]:
a=np.random.randint(1,50,9).reshape(3,3)
a

array([[16,  8,  6],
       [41, 13, 20],
       [11, 34, 17]])

In [6]:
# regularization term---> poooling layers--->
# minpooling
# maxpooling
# global average pooling


In [7]:
# stride-> gap or step value that is use for matrix choice
# kernal---> filteration


In [8]:
a

array([[16,  8,  6],
       [41, 13, 20],
       [11, 34, 17]])

In [9]:
# 2x2 kernal ---> stride=a
[16,8,41,13],[8,6,13,20]
[41,13,11,34],[13,20,34,17]

([41, 13, 11, 34], [13, 20, 34, 17])

In [11]:
# maxpooling ;layer--->
[41],[20],[41],[34]
# min pooling layer--->
[8],[6],[13],[13]
# global avrage pooling layer--->
# avrage of the given image basis on the data

SyntaxError: invalid syntax (ipython-input-3014050584.py, line 5)

In [12]:
a=np.random.randint(1,50,16).reshape(4,4)
a

array([[15, 37, 13,  6],
       [29, 45, 43, 35],
       [48, 26, 36,  1],
       [14,  5, 32, 12]])

In [13]:
# 2x2 kernal ---> stride=2
[16,8,41,13],[8,6,13,20]
[41,13,11,34],[13,20,34,17]

([41, 13, 11, 34], [13, 20, 34, 17])

In [14]:
# dense layer--> it is considerd as a fully connected layer and this output of first layer
# will be input of second layer. it is working like as a pipeline and we can ay it hidden layer


In [15]:
# convolutional layer-> it is considers as partially connected layer and in this we will detect specific parts

In [16]:
# pooling layer---> it is regularization techinique for image related data


In [19]:
# flatten layer--> it will convert higher dimension to lower dimension (1-d)

In [20]:
# workflow of cnn-->

In [21]:
# data ingestion--> data cleaning and preprocessing--> model sequential architecture
# CNN_1 layer
# pooling layer
# CNN_2 layer
# pooling layer
# flatten layer(it will convert into 1d)
# dense layer (pipeline)
# model complile
# model training
# model prediction
# model loss , accuracy