<a href="https://colab.research.google.com/github/sumitchhipa/python-learning/blob/main/function_transformer_scratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from sklearn.preprocessing import FunctionTransformer
import numpy as np
X=np.array([[1,2],[3,4]])
log_transform=FunctionTransformer(np.log1p)
X_transformed=log_transform.transform(X)
print(X_transformed)

[[0.69314718 1.09861229]
 [1.38629436 1.60943791]]


In [ ]:
from sklearn.preprocessing import FunctionTransformer
import numpy as np
X=np.array([[1,2],[3,4]])
def squ(X):
  return np.hstack((X,X**2))
custom_transform=FunctionTransformer(squ)
X_transformed=custom_transform.transform(X)
print(X_transformed)

[[ 1  2  1  4]
 [ 3  4  9 16]]


In [4]:
from sklearn.preprocessing import FunctionTransformer
import numpy as np
X=np.array([[1,2],[3,4]])
def my_scaling(X):
  return X/np.max(X)
custom_transform=FunctionTransformer(my_scaling)
X_transformed=custom_transform.transform(X)
print(X_transformed)

[[0.25 0.5 ]
 [0.75 1.  ]]


In [5]:
from sklearn.preprocessing import FunctionTransformer
import numpy as np
X=np.array([[1,2],[3,np.nan]])
def my_cleaing(X):
  X[np.isnan(X)]=0
  return X
custom_transform=FunctionTransformer(my_cleaing)
X_transformed=custom_transform.transform(X)
print(X_transformed)

[[1. 2.]
 [3. 0.]]


In [7]:
import numpy as np
import pandas as pd
df=pd.read_csv("/content/placement.csv")
df.head()

cgpa  resume_score  placed
0  8.14          6.52       1
1  6.17          5.17       0
2  8.27          8.86       1
3  6.88          7.27       1
4  7.52          7.30       1

In [9]:
x=df.drop(columns=["placed"])
y=df["placed"]

In [11]:
from sklearn.preprocessing import FunctionTransformer
log_transform=FunctionTransformer(np.log1p)
x_transformed=log_transform.fit_transform(x)
x_transformed

cgpa  resume_score
0   2.212660      2.017566
1   1.969906      1.819699
2   2.226783      2.288486
3   2.064328      2.112635
4   2.142416      2.116256
..       ...           ...
95  1.991976      1.998774
96  2.222459      2.170196
97  2.034706      2.172476
98  2.212660      1.891605
99  1.958685      2.029463

[100 rows x 2 columns]