<a href="https://colab.research.google.com/github/sumitchhipa/python-learning/blob/main/Numpy_day_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
# ones -> it will create an array in which all the values are 1.
import numpy as np
a=np.ones(4)
a


array([1., 1., 1., 1.])

In [11]:
# (3)eye()-> it will create an array in which diognal positional elements will be a and rest all are 0
a=np.eye(3)
a
# diag()-> using this method we can create an array in which we can customiz our digonal position elements.
a=np.diag([2,52,2,5])
a
# (5) random module
#A) Randint(-> it will genrate random numbers in a given range )
# syntax- np.random.randint(min_value,max_value,total_numbers)
a=np.random.randint(1,10,3)
a
# (b)-> rand() it will genrate random numbers in 0-1.
a=np.random.rand(3)
a
# (c)seed()-> it will fix the random genrated data
np.random.seed(1)
a= np.random.randint(1,10,4)
a

array([6, 9, 6, 1])

In [13]:
# view vs copy------>
a= np.array([1,2,3,4,5,7,8,9,10])
b=a[2:5]
b[:]=0
b
# a

array([ 1,  2,  0,  0,  0,  7,  8,  9, 10])

In [15]:
a=np.array([1,2,3,4,5,6,7,8,9])
b=a[1:5].copy()
b[:]=0
b
# a

array([0, 0, 0, 0])