<a href="https://colab.research.google.com/github/sumitchhipa/python-learning/blob/main/Numpy_day3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
# Reshaping array
# n(rows)*n(coloums)= n(total_elements)
total_elememts=12
# 1*12, 12*1
# 2*6,6*2
# 3*4,4*3
a=np.arange(1,13,1)
a
a.reshape(2,6)


array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [5]:
a.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [7]:
a.reshape(4,3)


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [8]:
a.reshape(6,3)

ValueError: cannot reshape array of size 12 into shape (6,3)

In [9]:
# opertaion on arary
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [10]:
a*3

array([ 3,  6,  9, 12])

In [11]:
a**2

array([ 1,  4,  9, 16])

In [14]:
a=np.arange(1,5).reshape(2,2)
a

array([[1, 2],
       [3, 4]])

In [15]:
b=np.arange(5,9).reshape(2,2)
b

array([[5, 6],
       [7, 8]])

In [16]:
a+b

array([[ 6,  8],
       [10, 12]])

In [17]:
a-b

array([[-4, -4],
       [-4, -4]])

In [18]:
a.dot(b)

array([[19, 22],
       [43, 50]])

In [27]:
a=np.arange(1,10).reshape(3,3)
a
np.sum(a)
# np.sum(a,axis=0)

np.int64(45)

In [25]:
np.sum(a,axis=1)

array([ 6, 15, 24])

In [33]:
# unique-> it will return unique element of array and its indexing and toatal accurance.
a=np.array([1,2,2,2,2,2,1,3,4,5,6])
np.unique(a,return_index=True,return_counts=True)


(array([1, 2, 3, 4, 5, 6]),
 array([ 0,  1,  7,  8,  9, 10]),
 array([2, 5, 1, 1, 1, 1]))

In [32]:
# linspace()-> it eill  create an array in which gap of values will be equal.
a=np.linspace(1,2,5)
a

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [38]:
# Hsatck and Vstack
a= np.array([1,2,3,4])
b= np.array([5,6,7,8])
c= np.array([9,1,0,11,12])
np.hstack((a,b,c))
# np.vstack((a,b,c))



array([ 1,  2,  3,  4,  5,  6,  7,  8,  9,  1,  0, 11, 12])