<a href="https://colab.research.google.com/github/sumitchhipa/python-learning/blob/main/TEST.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Q.1
# !pip install numpy
# Q.2
import numpy as np
a=np.array([1,2,3,4,5])
print(a)


[1 2 3 4 5]


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [2]:
#Q.3
a=np.arange(1,11,1)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
# Q.4
a=np.arange(10,21,1)
print(a)

[10 11 12 13 14 15 16 17 18 19 20]


In [5]:
# Q.5
a=np.array([1,2,3,4,56,5,6,5,6,5,5,5])
np.unique(a,return_counts=True)


(array([ 1,  2,  3,  4,  5,  6, 56]), array([1, 1, 1, 1, 5, 2, 1]))

In [11]:
# Q.6
a=np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3)

a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
# Q.7
a=np.array([[0,1,1],[0,1,1],[0,1,1]])
a

array([[0, 1, 1],
       [0, 1, 1],
       [0, 1, 1]])

In [15]:
# Q.7
a=np.array([[0,1,1],[0,1,1],[0,1,1]])
np.hstack(a)
np.vstack(a)

array([[0, 1, 1],
       [0, 1, 1],
       [0, 1, 1]])